### PR TITLE
Fixed some bugs

### LINKED ISSUE #236: notebook crafting not working
[aunis error.txt](https://github.com/MrJake222/AUNIS/files/5387951/aunis.error.txt)
crafting recipe not working.

### LINKED ISSUE #242: disconnect from the server while holding univers dialer and impossible to reconnect
This was written to the server console from my connection to my kick

```
[19:50:06] [Server thread/INFO] [minecraft/PlayerList]: FlynCZE[/89.203.217.72:64030] logged in with entity id 250482 at (-85.93853632614025, 68.0, -16.216694790571964)
[19:50:06] [Server thread/INFO] [minecraft/DedicatedServer]: FlynCZE joined the game
[19:50:06] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[19:50:06] [Server thread/INFO] [Mekanism]: Sent config to 'FlynCZE.'
[19:50:06] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[19:50:06] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/10)
[19:50:06] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /89.203.217.72:64030
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
[19:50:07] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[19:50:07] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/10)
[19:50:07] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /89.203.217.72:64030
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
[19:50:08] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[19:50:08] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/10)
[19:50:08] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /89.203.217.72:64030
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
[19:50:09] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[19:50:09] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/10)
[19:50:09] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /89.203.217.72:64030
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
[19:50:10] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[19:50:10] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/10)
[19:50:10] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /89.203.217.72:64030
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
[19:50:10] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: FlynCZE lost connection: Internal server error
[19:50:10] [Server thread/INFO] [minecraft/DedicatedServer]: FlynCZE left the game



and this was written to the server console when the uverse dialer is picked up


[20:16:16] [Server thread/WARN] [aunis]: Facing down when activating DHD
[20:16:16] [Server thread/WARN] [aunis]: Facing down when activating DHD
[20:16:19] [Server thread/WARN] [aunis]: Facing down when activating DHD
[20:16:19] [Server thread/WARN] [aunis]: Facing down when activating DHD
```

### LINKED ISSUE #243: instant crash from single player while holding universe dialer next to rings or universe gate
[2020-11-05-7.log](https://github.com/MrJake222/AUNIS/files/5497894/2020-11-05-7.log)
the log have to much characters so i upload the file

### LINKED ISSUE #249: [Issue - Mod Conflict] Kawoosh able to destroy blocks marked as non-destructible (RFTools Conflict)
The Kawoosh is able to destroy the shield blocks of RFTools' shield generators. Those blocks are meant to not be able to be destroyed no matter what. I have already communicated with RFTools' dev, they ascertained that the issue is in the kawoosh.

### PR DESCRIPTION
**Pull request by slava110**
- Updated Gradle to 4.8.1
- Updated Forge to 14.23.5.2847 and mappings snapshot_20171003
- Removed ConfigSlurper from build.gradle (you can use `gradle.properties`)
- Fixed #249 (Kawoosh able to destroy blocks marked as non-destructible)
- Fixed #243 (Universe dialer crash) [Temporary fix]
- Fixed #242 (Universe dialer crash) [Temporary fix]
- Fixed #236 (Notebook crafting error) [Temporary fix]
- Added `Keyboard.enableRepeatEvents()` to PageRenameGui (you can now hold buttons, yay)
- Added kawoosh-invincible blocks to config

### CODE REVIEW

**Comment by slava110** [comment]
Also here's mod jar
https://github.com/slava110/AUNIS/releases/tag/1.9.11-beta

Universe dialer crash & notebook crafting marked as temporary as I'm thinking about using capabilities instead of NBT to store data. Should be safer. But I'll need to keep compatibility with old NBT system too

**Comment by MrJake222** [comment]
> Universe dialer crash & notebook crafting marked as temporary as I'm thinking about using capabilities instead of NBT to store data. Should be safer. But I'll need to keep compatibility with old NBT system too

Don't. Capabilities are so unpredictable on creative and I think it's beyond my control. See the capacitors, disappearing charge. Universe dialer would be much, much worse...

I'll look into it soon, thanks for your contribution. I'm worried about the mappings, I've changes them the way there were because I think OpenComputers (If I recall correctly) had some weird issues.

**Comment by slava110** [comment]
> > Universe dialer crash & notebook crafting marked as temporary as I'm thinking about using capabilities instead of NBT to store data. Should be safer. But I'll need to keep compatibility with old NBT system too
> 
> Don't. Capabilities are so unpredictable on creative and I think it's beyond my control. See the capacitors, disappearing charge. Universe dialer would be much, much worse...
> 
> I'll look into it soon, thanks for your contribution. I'm worried about the mappings, I've changes them the way there were because I think OpenComputers (If I recall correctly) had some weird issues.

What exact issues could happen with capabilities? I only had an issue with capabilities and OpenComputers (on registration). Easy to fix tho
And what exact issues you had with new mappings and OpenComputers? I've used same mappings for OCRocketry mod and had no issues :I

**Comment by MrJake222** [comment]
> What exact issues could happen with capabilities? I only had an issue with capabilities and OpenComputers (on registration). Easy to fix tho

Take fully charged Capacitor Bank in creative mode. Switch it around a bit in slots and It'll lose it's charge. Capabilities will reset.

> And what exact issues you had with new mappings and OpenComputers? I've used same mappings for OCRocketry mod and had no issues :I

I don't remember exactly. But I think it crashed with no method found or something. Could be another mod though...

**Comment by slava110** [comment]
> Take fully charged Capacitor Bank in creative mode. Switch it around a bit in slots and It'll lose it's charge. Capabilities will reset.
Can't reproduce on forge 14.23.5.2855. Should I do it in my inventory or in container or... Stargate container?
> I don't remember exactly. But I think it crashed with no method found or something. Could be another mod though...
Oh, ye, could happen with mods which are using old forge. Like LibVulpes. Easy to fix tho - you can use it as compileOnly (provided) dependency

**Comment by MrJake222** [comment]
Thank you for your pull request <3 Sadly, I don't have much time these days, but that may change in February...

Btw, making each fix a separate commit simplifies reviewing changes a lot.

**Pull request merged**
