### PR TITLE
Added ability to configure audio distance for wormhole and added pulverizer recipe for Nq ore into shards

### PR DESCRIPTION
**Pull request by NovaXeros**
Rebalanced/normalized OGG sound files to not be so loud so that they can be attenuated properly via Forge without being deafening.

Slightly rebalanced the attenuation volume of the DHD buttons. (Related to issue https://github.com/MrJake222/AUNIS/issues/177)

Added a config option to allow a player/admin to customise how far a wormhole can be heard opening/closing via a simple multiplier. (Related to issues https://github.com/MrJake222/AUNIS/issues/177 and https://github.com/MrJake222/AUNIS/issues/45, and known bug #4 on the discord).

Added pulverizer recipes for Naquadah Ore into Naquadah Shards with increased yield (in balance with pre-existing Nq Ore into Molten Nq).

Comment for clarification added to Config options regarding my previous configuration of the wormhole instability threshold

### CODE REVIEW

**Comment by MrJake222** [comment]
Thanks for finding the solution for this one. I'm pretty sure I've asked on Forge's forum and nobody answered :( Do you plan on normalising other sounds as well?

**Comment by MrJake222** [comment]
I've turned the config option to 5 and the sound is ear-ripping. What am i doing wrong?

**Comment by NovaXeros** [comment]
Yeah, there was virtually no documentation on it, save for a scrappy article that noted that the getVolume aspect of playing a positioned sound wasn't actually related to the actual played VOLUME (ie, in dB), but was related instead to the attenuation distance of the sound.

As for the audio being eardrum destroying at 5, that's interesting, and completely not what I got earlier! Wormhole open/close or both sound? It's possible that I've not normalised the wormhole sounds enough. I gave them a VERY conservative normalization to -3dB and had very decent results.

Standby, looking into this urgently now!

**Comment by MrJake222** [comment]
It was signficantly higher than normal

**Comment by NovaXeros** [comment]
On review, the following adjustments need to be made to make this properly work:

- Multiplier should take affect at the SoundHelper level, as opposed to the Enum in order to ensure config changes are obeyed on the fly.
 
- Some gate noises that are affected by the multiplier (such as the wormholes) need to be further reduced in volume to avoid breaking eardrums (were previously the attenuation rates were compensating for these volumes)

- Some gate noises need to be added to the multiplier, such as chevrons locking, incoming lock, etc.

Will close this PR until the above is done.

**Pull request closed without merging**
