### PR TITLE
chore: upgrade to ForgeGradle 3

### PR DESCRIPTION
**Pull request by sentialx**
This PR upgrades to ForgeGradle 3, since 2 doesn't seem to work (at least for me).

### CODE REVIEW

**Comment by slava110** [comment]
FG 2 is broken, pls don't...

**Comment by sentialx** [comment]
Why though?

**Comment by slava110** [comment]
There are some issues related to it. Like access transformers from dependencies aren't applied. It's recommended to stay on FG 2.3 for 1.12

**Comment by sentialx** [comment]
Aight, closing.

**Comment by slava110** [comment]
What issues do you have related to FG 2? I can check it when I'll be at home. Or maybe it's something that I already saw before. Feel free to PM me on discord

**Comment by sentialx** [comment]
It couldn't resolve CofhCore, OpenComputers etc.
```
com.intellij.openapi.externalSystem.model.ExternalSystemException: Could not find RedstoneFlux.jar (deobf.cofh:RedstoneFlux:1.12-2.1.0.7).
Searched in the following locations:
    https://files.minecraftforge.net/maven/deobf/cofh/RedstoneFlux/1.12-2.1.0.7/RedstoneFlux-1.12-2.1.0.7.jar
> Could not find RedstoneFlux.jar (deobf.cofh:RedstoneFlux:1.12-2.1.0.7).
  Searched in the following locations:
      https://files.minecraftforge.net/maven/deobf/cofh/RedstoneFlux/1.12-2.1.0.7/RedstoneFlux-1.12-2.1.0.7.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 ```

**Pull request closed without merging**
